# Generated by Django 2.2 on 2022-10-29 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("NycBasics", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="amenity_model",
        ),
        migrations.DeleteModel(
            name="user_location_model",
        ),
    ]
