# Generated by Django 2.2 on 2022-11-04 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NycBasics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating_Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity_type', models.CharField(max_length=10)),
                ('rating', models.IntegerField()),
                ('review', models.CharField(max_length=255)),
                ('is_flagged', models.BooleanField(default=False, null=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('upvotes', models.IntegerField(default=0, null=True)),
                ('downvotes', models.IntegerField(default=0, null=True)),
                ('bench_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NycBasics.bench_model')),
                ('parking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NycBasics.parking_model')),
                ('toilet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NycBasics.toilet_model')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NycBasics.User')),
                ('water_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NycBasics.water_model')),
                ('wifi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NycBasics.wifi_model')),
            ],
        ),
    ]
