# Generated by Django 2.2 on 2022-11-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NycBasics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_otp",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="password_otp_timestamp",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="system_timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
