# Generated by Django 2.2 on 2022-11-22 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("NycBasics", "0002_auto_20221120_1529"),
    ]

    operations = [
        migrations.CreateModel(
            name="bookmark_model",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amenity_type", models.CharField(max_length=10, null=True)),
                ("amenity_id", models.IntegerField(default=0, null=True)),
                ("is_bookmarked", models.BooleanField(default=False, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="NycBasics.User"
                    ),
                ),
            ],
        ),
    ]
