# Generated by Django 2.2 on 2022-11-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NycBasics', '0002_auto_20221118_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='system_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
