# Generated by Django 2.2 on 2022-10-31 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("NycBasics", "0002_auto_20221030_2115"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
