# Generated by Django 2.2 on 2022-11-04 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("NycBasics", "0003_auto_20221104_1429"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rating_review",
            old_name="amenity",
            new_name="amenity_id",
        ),
    ]
