# Generated by Django 2.2 on 2022-11-29 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NycBasics', '0004_auto_20221127_2103'),
        ('NycBasics', '0004_auto_20221129_0030'),
    ]

    operations = [
    ]
